### ISSUE TITLE
Error: missing host permission for the tab, and any iframes

### ISSUE THREAD

**Issue by mattman71** [jscher2000/printable-print-doctor-extension#1]
Hi, I'm a new user to your extension, in a desperate search for a fix to my Firefox print-to-pdf problems.

In any case, when attempting to use it on a sample scrolling page to confirm I get more than one functional page of output, I encountered an error (the title of this issue) right away.

For reference, I clicked on the Call the doctor! extension icon, then the first button about unbreakable pages, while viewing [this page](https://support.mozilla.org/en-US/questions/1267149).

Is this a noob error? What am I doing wrong?

![image](https://user-images.githubusercontent.com/13487987/70830883-dd2a1f00-1db6-11ea-8615-e087b0f869fb.png)

**Comment by jscher2000** [comment]
Hi mattman71, the extension uses the activeTab permission to inject content scripts into the page. This is to avoid requiring "all URLs" permission. However, there are some limitations. 

One is, as you've discovered, restricted domains that no extensions are allowed to inject into, such as Mozilla Support and the Mozilla Add-ons site. You may need to use a different browser for that page. (There is a preference you can edit to remove one or more site restrictions, but because Mozilla sites may have elevated access to browser configuration, it is not recommended.)

The extension also won't have host permissions on frames loaded from other hosts, or "built-in" pages (including Reader view and the PDF Viewer).

**Comment by mattman71** [comment]
Ah, that makes sense. Thanks for the reply! I'll keep going and use it for my other problematic pages that I really need the help on.
